services:
  postgres:
    image: postgres:16-alpine
    container_name: tenpo_db
    environment:
      POSTGRES_DB: tenpo
      POSTGRES_USER: tenpo_user
      POSTGRES_PASSWORD: tenpo_password
      POSTGRES_INITDB_ARGS: "--locale=es_ES.utf8"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tenpo_user -d tenpo"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: tenpo_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  api:
    build: .
    container_name: tenpo_api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: tenpo
      DB_USER: tenpo_user
      DB_PASSWORD: tenpo_password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: "-Xms512m -Xmx512m -XX:+UseG1GC"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  default:
    name: tenpo_network 