spring:
  application:
    name: tenpo-challenge
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:tenpo}
    username: ${DB_USER:tenpo_user}
    password: ${DB_PASSWORD:tenpo_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 20000
      pool-name: TenpoHikariPool

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    org.hibernate: ERROR
    com.example.tenpochallenge: ERROR
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      host: redis
      port: 6379
  datasource:
    url: jdbc:postgresql://postgres:5432/tenpo
    username: tenpo_user
    password: tenpo_password